### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by maybenotilya** [iraedeus/test#1]
Добрый день! Увидел ваш проект и был впечатлен объемом проделанной работы. Надеюсь вы продолжите развивать этот репозиторий! Пожалуйста, добавьте описание проекта в README, чтобы разработчикам было проще в нем разобраться. Успехов вам!

**Comment by iraedeus** [comment]
> Добрый день! Увидел ваш проект и был впечатлен объемом проделанной работы. Надеюсь вы продолжите развивать этот репозиторий! Пожалуйста, добавьте описание проекта в README, чтобы разработчикам было проще в нем разобраться. Успехов вам!

Здравствуйте! Спасибо что интересуетесь нашими разработками. Мы прислушаемся к вашим советам и добавим описание проекта. Всего доброго
